services:
  - type: web
    name: acadexis-backend
    runtime: python
    pythonVersion: "3.12"
    plan: starter
    buildCommand: bash build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT Acadexis_backend.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Acadexis_backend.settings.production
    envVarGroups:
      - import: prod
    branches:
      - branch: main
        isProduction: true
      - branch: dev
    healthCheckPath: /api/auth/me/

  - type: background_worker
    name: acadexis-celery
    runtime: python
    pythonVersion: "3.12"
    plan: starter
    buildCommand: bash build.sh
    startCommand: celery -A Acadexis_backend worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Acadexis_backend.settings.production
    envVarGroups:
      - import: prod
    branches:
      - branch: main
        isProduction: true
      - branch: dev